#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Inhere\Console\IO\Input;
use Inhere\Console\IO\Output;
use Inhere\Console\Application;

use App\Config\Handler;
use App\Config\Server;
use App\Config\Process;
use Swolf\Core\Server\ServerFactory;

$meta = [
    'name' => Server::$setting['app_name'],
    'version' => Server::$setting['app_version'],
];
$input = new Input;
$output = new Output;
$app = new Application($meta, $input, $output);


/**
 * the priority of server's settings is:
 *      cli > config > default
 * which means if the commandline options is set and
 * different with config file, the options pointed by config file
 * will be override by commandline options.
 * if neither commandline or config file pointed required options,
 * the default value will be used.
 *
 */
$app->command('start', function (Input $in, Output $out) {

    $host = $in->getOption('h');
    $port = $in->getOption('p');
    $daemon = $in->getBoolOpt('d');

    if (function_exists('cli_set_process_title')) {
        cli_set_process_title(Server::$setting['app_name']);
    } else {
        swoole_set_process_name(Server::$setting['app_name']);
    }

    $serverConfig = new Server();

    $server = ServerFactory::instance($serverConfig);

    $server->run();

}, 'start application');


$app->command('restart', function (Input $in, Output $out) {


}, 'restart application');


$app->command('stop', function (Input $in, Output $out) {


    if (!file_exists())

        $pid = file_get_contents(Server::$setting['pid_file']);

    if (!posix_kill($pid, SIGKILL)) {
        $out->error('can not stop process ' . $pid, true);
    }

    unlink(Server::$setting['pid_file']);

}, 'stop application');

$app->command('status', function (Input $in, Output $out) {
    $command = sprintf('ps aux|grep \'%s\'|grep -v grep|wc -l', Server::$setting['app_name']);
    $processnum = system($command);
    if ($processnum > 0) {
        $out->info('server is running.');
    } else {
        $out->info('server is shutdown');
    }
}, 'show status of applicaiton');

$app->run();